### PR TITLE
Adjusted search dropdown to the left side

### PR DESCRIPTION
**Pull request by adina-hc**
Hi everyone, I've adjusted the width of the search dropdown as per specs of 'row' and setting "col s4" (added those classes, along with a list-competitions class to adjust the margin and pull it to the left side of the page. Please approve. Thanks!

### CODE REVIEW

**Review by izaack89 — CHANGES_REQUESTED** [review]
Need to change the index.html and dont upload the search.js

**Review by izaack89 — APPROVED** [review]
The code is good and can be merge into main

**Comment by adina-hc** [comment]
Closing this issue, div added with row class and modified from s4 to s3.

**Review by izaack89 — COMMENTED** [review]
The code is good and can be merge into main

**Pull request closed without merging**
